//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OzemstvoWindowsForm.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Rules : global::System.Configuration.ApplicationSettingsBase {
        
        private static Rules defaultInstance = ((Rules)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Rules())));
        
        public static Rules Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{Foo: \"Bar\"}")]
        public string Rule1 {
            get {
                return ((string)(this["Rule1"]));
            }
            set {
                this["Rule1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{Biz: \"Baz}")]
        public string Rule2 {
            get {
                return ((string)(this["Rule2"]));
            }
            set {
                this["Rule2"] = value;
            }
        }
    }
}
